// Cross-check the browser wallet against the Python node, byte for byte.
//
// vectors.json is generated by the Python side (src/wallet.py + Transaction) with
// FIXED private keys. Because signing is deterministic (RFC 6979 over SHA-256),
// the same key and message must yield the same address, canonical signing bytes,
// and signature in JavaScript. Run: `node --test` from frontend/.
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

import {
  Wallet,
  addressFromPublicKeyHex,
  canonicalJson,
  signingBytes,
} from '../src/services/wallet.js'

const here = dirname(fileURLToPath(import.meta.url))
const vectors = JSON.parse(readFileSync(join(here, 'vectors.json'), 'utf8'))
const dec = new TextDecoder()

test('canonicalJson matches Python json.dumps(sort_keys=True)', () => {
  assert.equal(
    canonicalJson({ b: 2, a: 1, nested: { y: 'x', a: 3 } }),
    '{"a": 1, "b": 2, "nested": {"a": 3, "y": "x"}}',
  )
})

for (const v of vectors) {
  test(`vector ${v.address.slice(0, 10)}… reproduces the Python values`, () => {
    const w = Wallet.fromPrivateKeyHex(v.private_key)

    // 1. Address and public key derive identically.
    assert.equal(w.publicKeyHex, v.public_key, 'public key')
    assert.equal(w.address, v.address, 'address')
    assert.equal(addressFromPublicKeyHex(v.public_key), v.address, 'address from pubkey')

    // 2. Canonical signing bytes are byte-identical to Python's.
    const tx = {
      type: 'standard',
      sender: v.address,
      recipient: v.recipient,
      amount: v.amount,
      timestamp: v.timestamp,
      nonce: v.nonce,
      metadata: v.metadata,
    }
    assert.equal(dec.decode(signingBytes(tx)), v.signing_bytes, 'signing bytes')

    // 3. The deterministic signature is byte-identical, so the Python node
    //    verifies it (verification is proven on the Python side in
    //    tests/integration/test_frontend_signatures.py).
    assert.equal(w.sign(signingBytes(tx)), v.signature, 'signature')

    // 4. signTransaction attaches the same signature + public key.
    const signed = w.signTransaction({ ...tx })
    assert.equal(signed.signature, v.signature)
    assert.equal(signed.public_key, v.public_key)
  })
}
